// Mock data for Collections page

export const mockCollections = [
  {
    id: 'my-1',
    name: 'Bourbon Mùa Thu Đặc Biệt',
    title: 'Bourbon Mùa Thu Đặc Biệt',
    description: 'Tuyển tập các công thức bourbon đặc biệt cho mùa thu với hương vị ấm áp.',
    category: 'cocktail',
    privacy: 'public',
    is_public: true,
    recipeCount: 12,
    viewCount: 234,
    updatedAt: '15/09/2026',
    author: {
      name: 'Minh Quân',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop',
    },
    tags: ['Bourbon', 'Mùa thu', 'Classic'],
    isBookmarked: false,
    cover_image: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=800&q=80',
    imageUrl: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=800&q=80',
    imageAlt: 'Bourbon Cocktail',
  },
  {
    id: 'my-2',
    name: 'Cocktail Không Cồn Cho Team',
    title: 'Cocktail Không Cồn Cho Team',
    description: 'Những mocktail sáng tạo cho những buổi tiệc không có rượu.',
    category: 'mocktail',
    privacy: 'private',
    is_public: false,
    recipeCount: 8,
    viewCount: 0,
    updatedAt: '10/09/2026',
    author: {
      name: 'Minh Quân',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop',
    },
    tags: ['Mocktail', 'Không cồn', 'Sáng tạo'],
    isBookmarked: true,
    cover_image: 'https://images.unsplash.com/photo-1544145945-f90425340c7e?w=800&q=80',
    imageUrl: 'https://images.unsplash.com/photo-1544145945-f90425340c7e?w=800&q=80',
    imageAlt: 'Mocktail',
  },
];

export const mockSystemCollections = [
  {
    id: 'sys-1',
    name: 'IBA Official Cocktails',
    title: 'IBA Official Cocktails',
    description: 'Danh mục công thức chuẩn quốc tế từ International Bartenders Association.',
    category: 'cocktail',
    privacy: 'public',
    is_public: true,
    recipeCount: 95,
    savedCount: 12500,
    viewCount: 45000,
    updatedAt: '01/09/2026',
    author: {
      name: 'IBA',
      avatar: 'https://via.placeholder.com/24',
    },
    tags: ['IBA', 'Quốc tế', 'Classic'],
    isBookmarked: false,
    badge: 'Chuẩn IBA',
    badgeColor: 'primary',
    cover_image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=800&q=80',
    imageUrl: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=800&q=80',
    imageAlt: 'IBA Cocktails',
    profileId: 1,
  },
  {
    id: 'sys-2',
    name: 'SCA Coffee Standards',
    title: 'SCA Coffee Standards',
    description: 'Tiêu chuẩn cà phê từ Specialty Coffee Association.',
    category: 'coffee',
    privacy: 'public',
    is_public: true,
    recipeCount: 42,
    savedCount: 8300,
    viewCount: 32000,
    updatedAt: '25/08/2026',
    author: {
      name: 'SCA',
      avatar: 'https://via.placeholder.com/24',
    },
    tags: ['SCA', 'Cà phê', 'Specialty'],
    isBookmarked: false,
    badge: 'SCA Certified',
    badgeColor: 'secondary',
    cover_image: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800&q=80',
    imageUrl: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800&q=80',
    imageAlt: 'SCA Coffee',
    profileId: 2,
  },
  {
    id: 'sys-3',
    name: 'Modern Mixology Techniques',
    title: 'Modern Mixology Techniques',
    description: 'Kỹ thuật pha chế hiện đại từ các bartenders hàng đầu thế giới.',
    category: 'cocktail',
    privacy: 'public',
    is_public: true,
    recipeCount: 28,
    savedCount: 5600,
    viewCount: 18000,
    updatedAt: '20/08/2026',
    author: {
      name: 'Mixology Master',
      avatar: 'https://via.placeholder.com/24',
    },
    tags: ['Kỹ thuật', 'Hiện đại', 'Master'],
    isBookmarked: true,
    badge: 'Chuyên sâu',
    badgeColor: 'primary',
    cover_image: 'https://images.unsplash.com/photo-1470337458703-46ad1756a187?w=800&q=80',
    imageUrl: 'https://images.unsplash.com/photo-1470337458703-46ad1756a187?w=800&q=80',
    imageAlt: 'Modern Mixology',
    profileId: 3,
  },
];

export const featuredArchive = {
  subtitle: 'Tuyển tập nổi bật',
  title: 'The Art of Espresso',
  description: 'Khám phá nghệ thuật pha chế espresso từ cơ bản đến chuyên sâu. Từ extraction rate, temperature, đến các kỹ thuật latte art.',
  recipeCount: 156,
  prepTime: '2-4 phút',
  clarityPercent: 94,
  updateInfo: 'Cập nhật tuần này',
};

export const FILTER_TABS = [
  { key: 'all', label: 'Tất cả' },
  { key: 'mine', label: 'Của tôi' },
  { key: 'popular', label: 'Phổ biến' },
  { key: 'recent', label: 'Mới nhất' },
];

export const COLLECTION_CATEGORIES = [
  { key: 'cocktail', label: 'Cocktail' },
  { key: 'mocktail', label: 'Mocktail' },
  { key: 'coffee', label: 'Cà phê' },
  { key: 'tea', label: 'Trà' },
  { key: 'beer', label: 'Bia' },
  { key: 'wine', label: 'Rượu vang' },
];

// Filter options for the filter panel
export const FILTER_OPTIONS = {
  topics: [
    { id: 'classic', label: 'Cổ điển', count: 45 },
    { id: 'modern', label: 'Hiện đại', count: 32 },
    { id: 'tropical', label: 'Nhiệt đới', count: 28 },
    { id: 'seasonal', label: 'Theo mùa', count: 21 },
    { id: 'party', label: 'Tiệc party', count: 18 },
    { id: 'health', label: 'Sức khỏe', count: 12 },
  ],
  categories: [
    { id: 'cocktail', label: 'Cocktail', count: 95 },
    { id: 'mocktail', label: 'Mocktail', count: 42 },
    { id: 'coffee', label: 'Cà phê', count: 38 },
    { id: 'tea', label: 'Trà', count: 25 },
    { id: 'beer', label: 'Bia', count: 15 },
    { id: 'wine', label: 'Rượu vang', count: 10 },
  ],
  flavors: [
    { id: 'sweet', label: 'Ngọt', count: 56 },
    { id: 'sour', label: 'Chua', count: 48 },
    { id: 'bitter', label: 'Đắng', count: 35 },
    { id: 'spicy', label: 'Cay', count: 22 },
    { id: 'smoky', label: 'Khói', count: 18 },
    { id: 'fruity', label: 'Hoa quả', count: 62 },
  ],
  difficulty: [
    { id: 'easy', label: 'Dễ', count: 45 },
    { id: 'medium', label: 'Trung bình', count: 38 },
    { id: 'hard', label: 'Khó', count: 22 },
    { id: 'expert', label: 'Chuyên gia', count: 12 },
  ],
};
