/**
 * Lineage Tree Data
 * Mock data cho 4 cây phả hệ cocktail kinh điển
 * Mỗi tree gồm: root → riffs[] → modern[] → crown
 */

export const lineageTrees = {
  old_fashioned: {
    id: 'old_fashioned',
    name: 'Old Fashioned & Manhattan',
    icon: 'local_bar',
    description: 'Dòng whiskey cocktail cổ điển bắt nguồn từ 1884',
    root: {
      id: 'root-01',
      title: 'Classic Whiskey Old Fashioned',
      year: 1884,
      origin: 'Pendennis Club, Louisville & Jerry Thomas Compendium',
      abv: '~34%',
      image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCcibtVt6HHaSab3ZBwP9QRQusv3poM2u1Dtmg2oo3ClPfEd8PQR3U8C1JbIPYw3rCIvx9w9VzFSdavcY81kYL9MYCTr6EPHGUsVqk7qnQCYdocrKVU6zzxkcq8bzHVN6kahKHlyKfX8IL-n9u9RpdyT9YqLkNRsHjopN_7lgLWGxBgfUy5qmR5Kquz98fHCTqNX7bochZFaaCGHUIy0Bn7dfx-VZCE2PTCMG26wPpuwPrjHKIM9woP',
      ratio: '60ml Rye/Bourbon, 1 viên đường mía, 2 dashes Angostura Bitters, tinh dầu cam',
    },
    riffs: [
      {
        id: 'riff-01',
        title: 'Boulevardier',
        year: 1927,
        era: 'Cấm Rượu',
        branch: 'Nhánh Paris Riff',
        description: 'Erskine Gwynne, Harry\'s New York Bar Paris. Hoán vị cấu trúc Bourbon bằng việc phối trộn Sweet Vermouth & Campari.',
        ratio: '45ml Bourbon + 30ml Sweet Vermouth + 30ml Campari',
      },
      {
        id: 'riff-02',
        title: 'Vieux Carré',
        year: 1938,
        era: 'Hậu Cấm Rượu',
        branch: 'Nhánh Creole',
        description: 'Walter Bergeron, Monteleone New Orleans. Cấu trúc phức hợp kết hợp Rye Whiskey với Cognac và rượu thảo mộc Bénédictine.',
        ratio: '30ml Rye + 30ml Cognac + 30ml Sweet Vermouth + Barspoon Bénédictine',
      },
      {
        id: 'riff-03',
        title: 'Sazerac',
        year: 1890,
        era: 'Tiền Cấm Rượu',
        branch: 'Nhánh Absinthe',
        description: 'Biểu tượng huyền thoại New Orleans: Thay thế ly ướp lạnh tráng rượu Absinthe Herbsaint sắc sảo kết hợp Peychaud\'s Bitters.',
        ratio: '60ml Rye + Tráng ly Absinthe + Đường viên + Peychaud\'s Bitters',
      },
    ],
    modern: [
      {
        id: 'modern-01',
        title: 'Left Hand Cocktail',
        year: 2008,
        era: 'NYC Craft',
        branch: 'Boulevardier →',
        icon: 'alt_route',
        description: 'Sam Ross (Milk & Honey). Đột biến thêm nốt đắng béo của Chocolate Mole Bitters vào bộ khung Boulevardier cổ điển.',
        ratio: 'Bourbon, Campari, Sweet Vermouth, 3 dashes Xocolatl Mole Bitters',
      },
      {
        id: 'modern-02',
        title: 'Smoked Oak & Honey Old Fashioned',
        year: 2018,
        era: 'Atelier Rev.',
        branch: 'Root →',
        icon: 'fireplace',
        description: 'Master Nguyễn Hoàng. Tác động khói gỗ sồi nướng cháy trực tiếp, thay thế đường mía bằng mật ong hoa rừng Tây Bắc ủ lạnh.',
        ratio: 'Rye Whiskey, Raw Wild Honey, Smoked Cherry Bitters, xông khói vòm ly',
      },
      {
        id: 'modern-03',
        title: 'Oaxaca Old Fashioned',
        year: 2007,
        era: 'Death & Co',
        branch: 'Root →',
        icon: 'psychology',
        description: 'Phil Ward. Cách mạng Agave thay thế Whiskey: Cân bằng Reposado Tequila kết hợp Mezcal khói và Agave Nectar đậm đặc.',
        ratio: '45ml Reposado Tequila, 15ml Mezcal, 1 barspoon Agave, 2 dashes Angostura',
      },
    ],
    crown: {
      id: 'crown-01',
      code: '#ARC-8942',
      title: 'Midnight Saffron Boulevardier',
      year: 2025,
      era: 'Atelier Đương Đại',
      description: 'Sáng tạo độc quyền tại trạm bar: Kỹ thuật Saffron Fat-wash trên nền Rye 100 Proof, kết hợp Campari xông gỗ táo và Sweet Vermouth ủ thảo mộc vùng Turin.',
      image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBEwhkapqbE_24Em0Ro7Yai5Lj6PRlxGS93moRwGCC7JSvHAzep2yQxLusDWZwH_77I1hBJDUWUlI4GHsTgMF3iw2PyJZFEcifIVdpixF0ypNL-VFkfz0iSYzSGAoZvNm22_VnFzXDXBmPZnDBIXF0C02cIjs8B7sz7tIbdsGJ7lQrU7TLRrRWE34f24QdKiPbMd9MOPz4ZJEK0ITPGLOuVe7kR9LnHFnTkUSB7QZz1gUvwjxffPlkd',
    },
    stats: {
      derivatives: 12,
      techniques: 3,
      artisans: 4,
    },
    comparison: [
      {
        generation: 'I',
        era: 'Gốc Tổ Tiên (1884)',
        title: 'Classic Old Fashioned',
        spirit: '60ml Kentucky Rye / Bourbon',
        spiritNote: 'Ngũ cốc nguyên bản, hương gỗ sồi vani ấm.',
        sweetener: '1 White Sugar Cube (Đường Mía)',
        sweetenerNote: 'Dầm tan chảy trực tiếp dưới đáy ly.',
        bitter: '2 Dashes Angostura Bitters',
        bitterNote: 'Vỏ quế, rễ cây khổ sâm Trinidad.',
        technique: 'Bày Vỏ Cam Tươi (Orange Twist)',
        techniqueNote: 'Vắt biểu bì tạo màng sương tinh dầu cam.',
        abv: '34%',
        brix: '4.2',
      },
      {
        generation: 'II',
        era: 'Cầu Nối Đột Biến (Rev. 1928)',
        title: 'Smoked Oak & Honey',
        spirit: '55ml Rye Whiskey High-Proof',
        spiritNote: 'Gia vị cay nồng hỗ trợ chịu tải khói.',
        sweetener: '10ml Mật Ong Rừng Ủ Sồi',
        sweetenerNote: 'Hạ vị gắt, tăng cường độ sánh mượt (mouthfeel).',
        bitter: 'Cherry Bark & Vanilla Bitters',
        bitterNote: 'Tạo lớp đắng êm dịu phong vị quả mọng.',
        technique: 'Xông Khói Gỗ Sồi Trực Tiếp',
        techniqueNote: 'Đốt dăm gỗ sồi Pháp trong vòm thủy tinh.',
        abv: '31%',
        brix: '6.8',
      },
      {
        generation: 'III',
        era: 'Atelier Đương Đại (2025)',
        title: 'Midnight Saffron Boulevardier',
        spirit: '40ml Saffron Washed Rye 100°',
        spiritNote: 'Ngâm chiết nhụy nghệ tây & lọc béo trong 48h.',
        sweetener: '30ml Sweet Vermouth Torino',
        sweetenerNote: 'Chứa hàm lượng đường nho tự nhiên & thảo mộc.',
        bitter: '30ml Campari Applewood Infused',
        bitterNote: 'Đắng rực rỡ kết hợp khói gỗ táo phương Bắc.',
        technique: 'Khói Lạnh & Sợi Saffron Tươi',
        techniqueNote: 'Sợi saffron dát lên khối đá tinh khiết 50mm.',
        abv: '27.5%',
        brix: '8.1',
      },
    ],
  },

  negroni: {
    id: 'negroni',
    name: 'Negroni & Boulevardier',
    icon: 'nightlife',
    description: 'Dòng bitter-forward cocktail Ý với Campari làm trung tâm',
    root: {
      id: 'root-negroni',
      title: 'Classic Negroni',
      year: 1919,
      origin: 'Caffè Casoni, Florence — Count Camillo Negroni',
      abv: '~28%',
      ratio: '30ml Gin + 30ml Sweet Vermouth + 30ml Campari',
    },
    riffs: [
      {
        id: 'riff-negroni-01',
        title: 'Negroni Sbagliato',
        year: 1972,
        era: 'Hậu Negroni',
        branch: 'Nhánh Ý',
        description: 'Mario Mihajlov (B Checker), Milan. Nhầm lẫn thần kỳ: Prosecco thay Gin tạo nên phiên bản long mình, effervescent.',
        ratio: '30ml Prosecco + 30ml Sweet Vermouth + 30ml Campari',
      },
      {
        id: 'riff-negroni-02',
        title: 'White Negroni',
        year: 2001,
        era: 'Modern',
        branch: 'Nhánh Trắng',
        description: 'Antonio Sperone, Turin. Bitter mềm hơn: Lillet Blanc thay Sweet Vermouth, Suze thay Campari tạo nốt thảo mộc đất.',
        ratio: 'Gin + Lillet Blanc + Suze + Vỏ chanh',
      },
      {
        id: 'riff-negroni-03',
        title: 'Boulevardier',
        year: 1927,
        era: 'Cấm Rượu',
        branch: 'Nhánh Paris Riff',
        description: 'Erskine Gwynne, Harry\'s New York Bar Paris. Hoán đổi Gin bằng Bourbon, tạo cấu trúc whiskey bitter hoàn chỉnh.',
        ratio: '45ml Bourbon + 30ml Sweet Vermouth + 30ml Campari',
      },
    ],
    modern: [
      {
        id: 'modern-negroni-01',
        title: 'Sbagliato Effervescente',
        year: 2022,
        era: 'Viral Sensation',
        branch: 'Negroni Sbagliato →',
        icon: 'bubble_chart',
        description: 'Chiến thắng viral của Matteo Correggia. Prosecco ngọt hơn, Campari giảm đắng, kết cấu bọt mịn.',
        ratio: 'Prosecco Dolce + Campari giảm 20% + Soda vỗ nhẹ',
      },
      {
        id: 'modern-negroni-02',
        title: 'Black Negroni',
        year: 2011,
        era: 'Modern',
        branch: 'White Negroni →',
        icon: 'contrast',
        description: 'Jeff "Burt" T. thách thức ranh giới đắng. Mezcal thay Gin, Aperol thay Campari tạo siêu đắng khói.',
        ratio: 'Mezcal + Aperol + Campari + Vermouth',
      },
      {
        id: 'modern-negroni-03',
        title: 'Cocchi Negroni',
        year: 2015,
        era: 'Tonalità',
        branch: 'Root →',
        icon: 'tune',
        description: 'D的努力: Giảm 50% Campari, thêm Cocchi Americano tạo độ axit và lavender, giảm ABV còn 18%.',
        ratio: '25ml Gin + 25ml Cocchi Americano + 15ml Campari',
      },
    ],
    crown: {
      id: 'crown-negroni-01',
      code: '#ARC-7741',
      title: 'Charred Cedar Negroni',
      year: 2025,
      era: 'Atelier Đương Đại',
      description: 'Charred Cedar fat-wash trên Gin London Dry, Campari smoked trên vỏ cam nướng, với một thanh chocolate đắng 85% đặt trên đá.',
      image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBEwhkapqbE_24Em0Ro7Yai5Lj6PRlxGS93moRwGCC7JSvHAzep2yQxLusDWZwH_77I1hBJDUWUlI4GHsTgMF3iw2PyJZFEcifIVdpixF0ypNL-VFkfz0iSYzSGAoZvNm22_VnFzXDXBmPZnDBIXF0C02cIjs8B7sz7tIbdsGJ7lQrU7TLRrRWE34f24QdKiPbMd9MOPz4ZJEK0ITPGLOuVe7kR9LnHFnTkUSB7QZz1gUvwjxffPlkd',
    },
    stats: {
      derivatives: 15,
      techniques: 4,
      artisans: 5,
    },
    comparison: [],
  },

  sour: {
    id: 'sour',
    name: 'Sour & Daisy',
    icon: 'spa',
    description: 'Dòng cocktail chua-ngọt với citrus và egg white foam',
    root: {
      id: 'root-sour',
      title: 'Whiskey Sour',
      year: 1872,
      origin: 'Jerry Thomas, How to Mix Drinks — Phiên bản gốc có cả lòng trắng trứng',
      abv: '~30%',
      ratio: '60ml Whiskey + 30ml Lemon juice + 15ml Simple syrup + 1 Egg white (tùy chọn)',
    },
    riffs: [
      {
        id: 'riff-sour-01',
        title: 'Daiquiri',
        year: 1896,
        era: 'Tiền Cấm Rượu',
        branch: 'Nhánh Cuba',
        description: 'Jennings Cox, Daiquiri Cuba. Biến tấu Rum với lime tươi và đường nghiền — nền tảng của tất cả Sour.',
        ratio: '60ml White Rum + 30ml Lime juice + 20ml Simple syrup 2:1',
      },
      {
        id: 'riff-sour-02',
        title: 'Amaretto Sour',
        year: 1960,
        era: 'Modern Classic',
        branch: 'Nhánh Liqueur',
        description: 'Biến tấu đại chúng với Amaretto và đệm thơm từ bourbon vanilla, thống trị ở mọi bar trên thế giới.',
        ratio: '45ml Amaretto + 30ml Lemon juice + 15ml Simple syrup + 2 dashes Angostura',
      },
      {
        id: 'riff-sour-03',
        title: 'Pisco Sour',
        year: 1924,
        era: 'Hậu Cấm Rượu',
        branch: 'Nhánh Nam Mỹ',
        description: 'Victor Vaughen Morris, Lima Peru. Pisco đặc trưng Peru kết hợp foam trứng và bọt mịn, gia vị Angostura trang trí.',
        ratio: '60ml Pisco + 30ml Lime juice + 20ml Simple syrup + 1 Egg white + 3 dashes Angostura',
      },
    ],
    modern: [
      {
        id: 'modern-sour-01',
        title: 'Clarified Milk Punch',
        year: 2013,
        era: 'Modern',
        branch: 'Daiquiri →',
        icon: 'science',
        description: 'Dave Arnold, Booker & Dax NY. Đục sữa và lọc trong — tạo màu sữa mịn đục nhưng vị trong vắt, không foam.',
        ratio: 'Rum + Citrus + Milk → Lọc → Rượu mạnh ẩM giảm 40%',
      },
      {
        id: 'modern-sour-02',
        title: 'Emotionally Confused Sour',
        year: 2019,
        era: 'Atelier Rev.',
        branch: 'Sour →',
        icon: 'mood',
        description: 'Toni Mora, Barcelona. Kết hợp tất cả các loại citrus (lemon + lime + yuzu + grapefruit) tạo phức hợp axit 7 chiều.',
        ratio: 'Vodka + 15ml mỗi citrus + 20ml Agave + Yuzu bitters',
      },
      {
        id: 'modern-sour-03',
        title: 'Barrel-Aged Daiquiri',
        year: 2015,
        era: 'Craft',
        branch: 'Daiquiri →',
        icon: 'wine_bar',
        description: 'Guillermo at Smuggler\'s Cove. Ủ Daiquiri trong thùng gỗ sồi 4 tuần — hấp thụ vani, tannin nhẹ, thay đổi cấu trúc.',
        ratio: 'White Rum ủ 4 tuần + Lime juice + Demerara syrup 2:1',
      },
    ],
    crown: {
      id: 'crown-sour-01',
      code: '#ARC-6612',
      title: 'Yuzu Cloud Sour',
      year: 2025,
      era: 'Atelier Đương Đại',
      description: 'Gelatin foam Yuzu với texture cloud-mousse, Whiskey bourbon giảm ABV còn 22% bằng citrus sparkling water, hoa elderflower essence.',
      image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBEwhkapqbE_24Em0Ro7Yai5Lj6PRlxGS93moRwGCC7JSvHAzep2yQxLusDWZwH_77I1hBJDUWUlI4GHsTgMF3iw2PyJZFEcifIVdpixF0ypNL-VFkfz0iSYzSGAoZvNm22_VnFzXDXBmPZnDBIXF0C02cIjs8B7sz7tIbdsGJ7lQrU7TLRrRWE34f24QdKiPbMd9MOPz4ZJEK0ITPGLOuVe7kR9LnHFnTkUSB7QZz1gUvwjxffPlkd',
    },
    stats: {
      derivatives: 18,
      techniques: 5,
      artisans: 6,
    },
    comparison: [],
  },

  highball: {
    id: 'highball',
    name: 'Highball & Fizz',
    icon: 'sailing',
    description: 'Dòng cocktail long drink với soda và đá',
    root: {
      id: 'root-highball',
      title: 'Whisky Highball',
      year: 1900,
      origin: 'Japan — Suntory popularised whisky highball để phục vụ trong các yakitori bar',
      abv: '~8-12%',
      ratio: '45ml Whisky + Tonic/Soda + Đá',
    },
    riffs: [
      {
        id: 'riff-highball-01',
        title: 'Gin & Tonic',
        year: 1783,
        era: 'Thực Dân',
        branch: 'Nhánh Y Tế',
        description: 'Quân đội Anh tại Ấn Độ pha Quinine (Tonic) với Gin để uống thuốc bổ hàng ngày. Điểu kiện thời tiết nhiệt đới.',
        ratio: '45ml London Dry Gin + 120ml Tonic water + Lime wedge',
      },
      {
        id: 'riff-highball-02',
        title: 'Tom Collins',
        year: 1874,
        era: 'Hậu Nội Chiến',
        branch: 'Nhánh Collins',
        description: 'John DeVere Collins, Limmer\'s Hotel London. Gin + Lemon + Sugar + Soda trong bình Collins — một trong những long drink đầu tiên.',
        ratio: '60ml Gin + 30ml Lemon juice + 20ml Simple syrup + Soda',
      },
      {
        id: 'riff-highball-03',
        title: 'Moscow Mule',
        year: 1941,
        era: 'Chiến Tranh',
        branch: 'Nhánh Mule',
        description: 'Wes Price & Jack Morgan, Chasen's LA. Sáng tạo để bán Vodka & ginger beer mới — copper mug trở thành biểu tượng.',
        ratio: '60ml Vodka + 120ml Ginger Beer + 15ml Lime juice',
      },
    ],
    modern: [
      {
        id: 'modern-highball-01',
        title: 'Japanese Highball',
        year: 2008,
        era: 'Craft',
        branch: 'Root →',
        icon: 'import_contacts',
        description: 'Toshiyuki Saito, Tokyo. Highball Nhật Bản: whisky giảm ABV 7-8%, soda lạnh từ siphon, kỹ thuật hoshi (đá hình sao).',
        ratio: '30ml Japanese Whisky + 180ml Soda lạnh từ siphon + Đá hình sao',
      },
      {
        id: 'modern-highball-02',
        title: 'Espresso Martini',
        year: 1983,
        era: 'London Scene',
        branch: 'Vodka Soda →',
        icon: 'coffee',
        description: 'Dick Bradsell, Soho Brasserie. Sáng tạo cho nữ khách muốn "wake me up then f*** me up" — coffee + vodka.',
        ratio: '50ml Vodka + 30ml Fresh espresso + 10ml Coffee liqueur',
      },
      {
        id: 'modern-highball-03',
        title: 'Aperol Spritz',
        year: 1919,
        era: 'Prosecco Era',
        branch: 'Wine Spritz →',
        icon: 'celebration',
        description: 'Phổ biến từ Veneto, trở thành hiện tượng toàn cầu 2010s. Aperol giảm đắng, Prosecco effervescent, màu cam rực rỡ.',
        ratio: '60ml Aperol + 90ml Prosecco + Splash Soda',
      },
    ],
    crown: {
      id: 'crown-highball-01',
      code: '#ARC-5503',
      title: 'Kyoto Fizz',
      year: 2025,
      era: 'Atelier Đương Đại',
      description: 'Kombu (tảo) dashi-washed Gin, yuzu juice, hime uchinoco shochu giảm ABV, sparkling water từ Hokkaido, hoa sakura salt rim.',
      image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBEwhkapqbE_24Em0Ro7Yai5Lj6PRlxGS93moRwGCC7JSvHAzep2yQxLusDWZwH_77I1hBJDUWUlI4GHsTgMF3iw2PyJZFEcifIVdpixF0ypNL-VFkfz0iSYzSGAoZvNm22_VnFzXDXBmPZnDBIXF0C02cIjs8B7sz7tIbdsGJ7lQrU7TLRrRWE34f24QdKiPbMd9MOPz4ZJEK0ITPGLOuVe7kR9LnHFnTkUSB7QZz1gUvwjxffPlkd',
    },
    stats: {
      derivatives: 20,
      techniques: 6,
      artisans: 7,
    },
    comparison: [],
  },
};

export const ERAS = [
  { key: 'all', label: 'Tất Cả Thời Kỳ' },
  { key: 'golden', label: 'Kỷ Nguyên Vàng (1880 - 1920)' },
  { key: 'prohibition', label: 'Thời Kỳ Cấm Rượu (1920 - 1933)' },
  { key: 'modern', label: 'Phục Hưng Hiện Đại (2000 - Nay)' },
];

export const FAMILY_IDS = ['old_fashioned', 'negroni', 'sour', 'highball'];
